
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })
import Footer from '@/components/footer/Footer'
export const metadata = {
  title: 'Gift City',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" sm:mt-0 sm:m-8 ">
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
